# Generated by Django 6.1.1 on 2026-09-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='Positive = add, Negative = remove', max_digits=10)),
                ('reason', models.CharField(choices=[('purchase', 'Purchase / Restock'), ('consumption', 'Consumption'), ('waste', 'Waste / Spoilage'), ('correction', 'Manual Correction'), ('return', 'Return to Supplier')], default='correction', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.ingredient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
